### ISSUE TITLE
[BUG] D4RL [antmaze / maze] doesn't work in d3rlpy

### ISSUE THREAD

**Issue by chwoong** [takuseno/d3rlpy#337]
Hi,
Thank you for your fantastic library.

As you mentioned in https://github.com/takuseno/d3rlpy/issues/323, D4RL requires `gym<0.24.0` while d3rlpy requires `gym>=0.26.0` for interface compatibility.

The `Hopper` or `Walker2d` datasets are fine. However, when I ran the code for the`Antmaze` or `maze2d` datasets in D4RL, 
```
python ./reproductions/offline/iql.py --dataset antmaze-medium-play-v2 --gpu 0
```
I got the following error.

`TypeError: MujocoEnv.__init__() missing 1 required positional argument: 'observation_space'`

The error occurs because `gym==0.26.0` requires observation_space as a positional argument, but the D4RL implementation (on`gym==0.23.0`) doesn't have the argument.

Please see
`gym==0.26.0` 
https://github.com/openai/gym/blob/dcd185843a62953e27c2d54dc8c2d647d604b635/gym/envs/mujoco/mujoco_env.py#L308
and
`D4RL antmaze`
https://github.com/Farama-Foundation/D4RL/blob/71a9549f2091accff93eeff68f1f3ab2c0e0a288/d4rl/locomotion/ant.py#L53

Could you tell me how to experiment with `antmaze` or `maze2d`?

**Comment by takuseno** [comment]
@chwoong Thanks for the issue! I need to investigate this. I believe this is something I missed when I upgrade `d3rlpy` to v2. For the mean time, you can use `d3rlpy==1.1.1` that uses the older version of gym. This is the script for `1.1.1`.
https://github.com/takuseno/d3rlpy/blob/v1.1.1/reproductions/offline/iql.py

**Comment by takuseno** [comment]
@chwoong Sorry, it took long to resolve this issue. But, thanks to @grahamannett 's PR that supports Minari datasets,  the fine-tuning reproduction scripts are finally working again!
